# Generated by Django 5.2.8 on 2025-12-29 09:00

import accounts.fields
import ai_model_server.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFeatureVector',
            fields=[
                ('clinical_vector_id', models.AutoField(primary_key=True, serialize=False)),
                ('includes_lab', models.BooleanField(default=False)),
                ('includes_diagnosis', models.BooleanField(default=False)),
                ('includes_vital', models.BooleanField(default=False)),
                ('includes_anthropometric', models.BooleanField(default=False)),
                ('extraction_model', models.CharField(blank=True, max_length=20, null=True)),
                ('model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('vector_dim', models.IntegerField(default=128)),
                ('feature_vector', ai_model_server.fields.VectorField(blank=True, dimensions=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.encounter')),
            ],
            options={
                'verbose_name': '임상 특징 벡터',
                'verbose_name_plural': '임상 특징 벡터',
                'db_table': 'hospital"."clinical_feature_vectors',
            },
        ),
        migrations.CreateModel(
            name='GenomicFeatureVector',
            fields=[
                ('genomic_vector_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssgsea_version', models.CharField(blank=True, max_length=20, null=True)),
                ('pathway_count', models.IntegerField(blank=True, null=True)),
                ('extraction_model', models.CharField(blank=True, max_length=20, null=True)),
                ('model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('vector_dim', models.IntegerField(default=512)),
                ('feature_vector', ai_model_server.fields.VectorField(blank=True, dimensions=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genomic', models.ForeignKey(db_column='genomic_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.genomicdata')),
            ],
            options={
                'verbose_name': '유전체 특징 벡터',
                'verbose_name_plural': '유전체 특징 벡터',
                'db_table': 'hospital"."genomic_feature_vectors',
            },
        ),
        migrations.CreateModel(
            name='RadioFeatureVector',
            fields=[
                ('radio_vector_id', models.AutoField(primary_key=True, serialize=False)),
                ('extraction_model', models.CharField(blank=True, max_length=20, null=True)),
                ('model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('vector_dim', models.IntegerField(default=2048)),
                ('feature_vector', ai_model_server.fields.VectorField(blank=True, dimensions=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyairun')),
                ('series', models.ForeignKey(db_column='series_uid', on_delete=django.db.models.deletion.CASCADE, to='radiology.dicomseries')),
            ],
            options={
                'verbose_name': '영상 특징 벡터',
                'verbose_name_plural': '영상 특징 벡터',
                'db_table': 'hospital"."radio_feature_vectors',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=20)),
                ('model_config', models.JSONField(blank=True, null=True)),
                ('prediction_results', models.JSONField()),
                ('confidence_scores', models.JSONField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('risk_group', accounts.fields.RiskGroupField(blank=True, choices=[('LOW', '저위험'), ('MEDIUM', '중위험'), ('HIGH', '고위험')], max_length=10, null=True)),
                ('risk_factors', models.JSONField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('shap_values', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('status', accounts.fields.StatusField(choices=[('PENDING', '대기'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.encounter')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.patient')),
                ('clinical_vector', models.ForeignKey(blank=True, db_column='clinical_vector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model_server.clinicalfeaturevector')),
                ('genomic_vector', models.ForeignKey(blank=True, db_column='genomic_vector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model_server.genomicfeaturevector')),
                ('imaging_vector', models.ForeignKey(blank=True, db_column='imaging_vector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model_server.radiofeaturevector')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과',
                'db_table': 'hospital"."ai_analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_id', 'task_type'], name='idx_patient_task'), models.Index(fields=['encounter_id', 'task_type'], name='idx_encounter_task'), models.Index(fields=['task_type', 'status'], name='idx_task_status'), models.Index(fields=['created_at'], name='idx_created')],
            },
        ),
    ]
