# Generated by Django 5.2.8 on 2026-01-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_model_server', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='encounter',
            field=models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.encounter'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='genomic',
            field=models.ForeignKey(blank=True, db_column='genomic_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.genomicdata'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='clinicalfeaturevector',
            name='encounter',
            field=models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.encounter'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='clinical_vector',
            field=models.ForeignKey(blank=True, db_column='clinical_vector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model_server.clinicalfeaturevector'),
        ),
    ]
