# Generated by Django 5.2.8 on 2026-01-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_model_server', '0002_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiofeaturevector',
            name='run',
            field=models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, to='radiology.radiologyairun'),
        ),
        migrations.AddField(
            model_name='radiofeaturevector',
            name='series',
            field=models.ForeignKey(db_column='series_uid', on_delete=django.db.models.deletion.CASCADE, to='radiology.dicomseries'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='imaging_vector',
            field=models.ForeignKey(blank=True, db_column='imaging_vector_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_model_server.radiofeaturevector'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['patient_id', 'task_type'], name='idx_patient_task'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['encounter_id', 'task_type'], name='idx_encounter_task'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['task_type', 'status'], name='idx_task_status'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['created_at'], name='idx_created'),
        ),
    ]
