# Generated by Django 5.2.8 on 2026-01-09 01:07

import ai_model_server.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model_server', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiofeaturevector',
            name='feature_vector',
            field=ai_model_server.fields.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AlterField(
            model_name='radiofeaturevector',
            name='vector_dim',
            field=models.IntegerField(default=512),
        ),
    ]
