# Generated by Django 5.2.8 on 2025-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
