# Generated by Django 5.2.7 on 2025-12-23 02:24

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("administration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisType",
            fields=[
                (
                    "diagnosis_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "detail_table",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": 'hospital"."diagnosis_types',
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_no", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("license_no", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("room_number", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "의사",
                "verbose_name_plural": "의사",
                "db_table": 'hospital"."doctor',
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                ("clinic_room", models.CharField(blank=True, max_length=20, null=True)),
                ("encounter_date", models.DateField()),
                ("encounter_time", models.TimeField()),
                (
                    "encounter_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("checkin_time", models.DateTimeField(blank=True, null=True)),
                ("encounter_start", models.TimeField(blank=True, null=True)),
                ("encounter_end", models.TimeField(blank=True, null=True)),
                ("is_first_visit", models.BooleanField(default=False)),
                ("chief_complaint", models.TextField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True, null=True)),
                ("lab_recorded", models.BooleanField(default=False)),
                ("ct_recorded", models.BooleanField(default=False)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnosis_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="diagnosis_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.diagnosistype",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        db_column="staff_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="administration.administration",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."encounters',
                "ordering": ["-encounter_date", "-encounter_time"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("sample_id", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    accounts.fields.GenderField(blank=True, max_length=10, null=True),
                ),
                (
                    "current_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        db_column="doctor_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.doctor",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."patient',
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                ("lab_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_date", models.DateField()),
                (
                    "afp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "bilirubin_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pt_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("platelet", models.IntegerField(blank=True, null=True)),
                (
                    "creatinine",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "child_pugh_class",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("meld_score", models.IntegerField(blank=True, null=True)),
                (
                    "albi_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("albi_grade", models.CharField(blank=True, max_length=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("measured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."lab_results',
            },
        ),
        migrations.CreateModel(
            name="ImagingOrder",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("modality", models.CharField(max_length=16)),
                ("body_part", models.CharField(blank=True, max_length=64, null=True)),
                ("order_notes", models.TextField(blank=True, null=True)),
                ("priority", models.CharField(default="ROUTINE", max_length=10)),
                ("status", models.CharField(default="REQUESTED", max_length=20)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("study_uid", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."imaging_orders',
            },
        ),
        migrations.CreateModel(
            name="HCCDiagnosis",
            fields=[
                ("hcc_id", models.AutoField(primary_key=True, serialize=False)),
                ("hcc_diagnosis_date", models.DateField()),
                ("ajcc_stage", models.CharField(blank=True, max_length=10, null=True)),
                ("ajcc_t", models.CharField(blank=True, max_length=10, null=True)),
                ("ajcc_n", models.CharField(blank=True, max_length=10, null=True)),
                ("ajcc_m", models.CharField(blank=True, max_length=10, null=True)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "vascular_invasion",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ishak_score", models.IntegerField(blank=True, null=True)),
                (
                    "hepatic_inflammation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ecog_score", models.IntegerField(blank=True, null=True)),
                (
                    "tumor_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("measured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."hcc_diagnosis',
            },
        ),
        migrations.CreateModel(
            name="GenomicData",
            fields=[
                ("genomic_id", models.AutoField(primary_key=True, serialize=False)),
                ("sample_date", models.DateField(blank=True, null=True)),
                ("pathway_scores", models.JSONField(blank=True, null=True)),
                ("lasso_coefficients", models.JSONField(blank=True, null=True)),
                ("risk_genes", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("measured_at", models.DateTimeField(blank=True, null=True)),
                ("sample_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."genomic_data',
            },
        ),
        migrations.AddField(
            model_name="encounter",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.patient",
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "appointment_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        db_column="staff_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.administration",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        db_column="doctor_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."appointments',
            },
        ),
        migrations.CreateModel(
            name="AnthropometricData",
            fields=[
                ("anthro_id", models.AutoField(primary_key=True, serialize=False)),
                ("measured_at", models.DateField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("is_pregnant", models.BooleanField(default=False)),
                ("smoking_status", models.BooleanField(default=False)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."anthropometric_data',
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("prescription_date", models.DateField()),
                ("item_seq", models.BigIntegerField()),
                ("medication_name", models.CharField(max_length=200)),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("duration_days", models.IntegerField(blank=True, null=True)),
                ("pharmacy_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("measured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.department",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctor.doctor",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."prescriptions',
            },
        ),
        migrations.CreateModel(
            name="ScheduleDoctor",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("schedule_date", models.DateField()),
                (
                    "schedule_type",
                    accounts.fields.DoctorScheduleTypeField(max_length=30),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("clinic_room", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="doctor.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "의사 일정",
                "verbose_name_plural": "의사 일정",
                "db_table": 'hospital"."schedule_doctor',
                "ordering": ["-schedule_date"],
            },
        ),
        migrations.CreateModel(
            name="VitalData",
            fields=[
                ("vital_id", models.AutoField(primary_key=True, serialize=False)),
                ("measured_at", models.DateField()),
                ("sbp", models.IntegerField(blank=True, null=True)),
                ("dbp", models.IntegerField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."vital_data',
            },
        ),
    ]
