# Generated by Django 5.2.8 on 2026-01-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                db_column="assigned_doctor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_encounters",
                to="doctor.doctor",
            ),
        ),
    ]
