# Generated by Django 5.2.8 on 2025-12-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_status',
            field=models.CharField(blank=True, choices=[('SCHEDULED', '예약됨'), ('WAITING', '대기중'), ('IN_PROGRESS', '진료중'), ('COMPLETED', '완료'), ('CANCELLED', '취소'), ('NO_SHOW', '노쇼')], default='SCHEDULED', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagingorder',
            name='status',
            field=models.CharField(choices=[('REQUESTED', '요청됨'), ('WAITING', '촬영대기'), ('IN_PROGRESS', '촬영중'), ('COMPLETED', '완료'), ('REPORTED', '판독완료'), ('CANCELLED', '취소')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_status',
            field=models.CharField(blank=True, choices=[('REGISTERED', '접수완료'), ('WAITING_CLINIC', '진료대기'), ('IN_CLINIC', '진료중'), ('WAITING_IMAGING', '촬영대기'), ('IN_IMAGING', '촬영중'), ('WAITING_LAB', '검사대기'), ('IN_LAB', '검사중'), ('COMPLETED', '당일진료완료'), ('DISCHARGED', '퇴원')], default='REGISTERED', max_length=30, null=True),
        ),
    ]
