# Generated by Django 5.2.8 on 2026-01-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_encounter_assigned_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctortoradiologyorder",
            name="medical_record",
        ),
        migrations.AddField(
            model_name="doctortoradiologyorder",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="encounter_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.encounter",
            ),
        ),
    ]
