# Generated by Django 5.2.8 on 2026-01-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_patient_patient_name_674907_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="order_notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("BLOOD_LIVER", "간기능 혈액검사"),
                    ("GENOMIC", "유전체 분석"),
                    ("PHYSICAL", "신체 계측"),
                    ("VITAL", "바이탈 측정"),
                ],
                max_length=20,
            ),
        ),
    ]
