# Generated by Django 5.2.8 on 2026-01-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_laborder_order_notes_alter_laborder_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "요청됨"),
                    ("REGISTERED", "접수완료"),
                    ("WAITING_CLINIC", "진료대기"),
                    ("IN_CLINIC", "진료중"),
                    ("WAITING_RESULTS", "결과대기"),
                    ("WAITING_IMAGING", "촬영대기"),
                    ("IN_IMAGING", "촬영중"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "취소"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
