# Generated by Django 5.2.8 on 2026-01-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_encounter_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitaldata',
            name='medical_record',
            field=models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.medicalrecord'),
        ),
    ]
