# Generated by Django 5.2.8 on 2026-01-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_vitaldata_medical_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hccdiagnosis',
            name='medical_record',
            field=models.ForeignKey(blank=True, db_column='record_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.medicalrecord'),
        ),
    ]
