# Generated by Django 5.2.8 on 2026-01-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_encounter_workflow_state'),
        ('doctor', '0009_alter_hccdiagnosis_medical_record'),
    ]

    operations = [
    ]
