# Generated by Django 5.2.8 on 2026-01-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_merge_20260112_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='doctortoradiologyorder',
                    table='hospital"."doctor_to_radiology_orders',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE SCHEMA IF NOT EXISTS hospital;
                        ALTER TABLE IF EXISTS doctor_doctortoradiologyorder SET SCHEMA hospital;
                        ALTER TABLE IF EXISTS doctor_to_radiology_orders SET SCHEMA hospital;
                        ALTER TABLE IF EXISTS hospital.doctor_doctortoradiologyorder RENAME TO doctor_to_radiology_orders;
                    """,
                    reverse_sql="""
                        ALTER TABLE IF EXISTS hospital.doctor_to_radiology_orders SET SCHEMA public;
                        ALTER TABLE IF EXISTS public.doctor_to_radiology_orders RENAME TO doctor_doctortoradiologyorder;
                    """,
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="scheduledoctor",
            name="clinic_room",
        ),
    ]
