# Generated by Django 5.2.8 on 2026-01-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_merge_20260112_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={},
        ),
        migrations.AlterModelTable(
            name='doctortoradiologyorder',
            table='hospital"."doctor_to_radiology_orders',
        ),
        migrations.RemoveField(
            model_name="scheduledoctor",
            name="clinic_room",
        ),
    ]
