# Generated by Django 5.2.8 on 2026-01-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_alter_encounter_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'doctor_doctortoradiologyorder') THEN
                            ALTER TABLE "public"."doctor_doctortoradiologyorder" SET SCHEMA "hospital";
                        END IF;
                        
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'hospital' AND tablename = 'doctor_doctortoradiologyorder') THEN
                            ALTER TABLE "hospital"."doctor_doctortoradiologyorder" RENAME TO "doctor_to_radiology_orders";
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'hospital' AND tablename = 'doctor_to_radiology_orders') THEN
                            ALTER TABLE "hospital"."doctor_to_radiology_orders" RENAME TO "doctor_doctortoradiologyorder";
                            ALTER TABLE "hospital"."doctor_doctortoradiologyorder" SET SCHEMA "public";
                        END IF;
                    END
                    $$;
                    """
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="doctortoradiologyorder",
                    table='hospital"."doctor_to_radiology_orders',
                ),
            ]
        )
    ]
