# Generated by Django 5.2.8 on 2026-01-15 06:51

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0015_vitaldata_heart_rate_vitaldata_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledoctor",
            name="schedule_type",
            field=accounts.fields.DoctorScheduleTypeField(
                choices=[("OUTPATIENT", "외래"), ("SURGERY", "수술")], max_length=30
            ),
        ),
    ]
