# Generated by Codex on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0017_alter_encounter_workflow_state_add_waiting_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "요청됨"),
                    ("REGISTERED", "접수완료"),
                    ("WAITING_ORDER", "오더중"),
                    ("WAITING_CLINIC", "진료대기"),
                    ("WAITING_ADDITIONAL_CLINIC", "추가진료대기"),
                    ("IN_CLINIC", "진료중"),
                    ("WAITING_RESULTS", "결과대기"),
                    ("WAITING_IMAGING", "촬영대기"),
                    ("IN_IMAGING", "촬영중"),
                    ("WAITING_PAYMENT", "수납대기"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "취소"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
    ]
