# Generated by Codex on 2026-01-27

import django.db.models.deletion
from django.db import migrations, models


def backfill_encounter_ids(apps, schema_editor):
    MedicalRecord = apps.get_model("doctor", "MedicalRecord")

    record_to_encounter = dict(
        MedicalRecord.objects.exclude(encounter_id__isnull=True).values_list(
            "record_id",
            "encounter_id",
        )
    )
    if not record_to_encounter:
        return

    def update_model(model_name):
        Model = apps.get_model("doctor", model_name)
        rows = Model.objects.filter(
            medical_record_id__isnull=False,
            encounter_id__isnull=True,
        ).values_list("pk", "medical_record_id")
        to_update = []
        for pk, record_id in rows:
            encounter_id = record_to_encounter.get(record_id)
            if encounter_id:
                to_update.append(Model(pk=pk, encounter_id=encounter_id))
        if to_update:
            Model.objects.bulk_update(to_update, ["encounter"])

    update_model("VitalData")
    update_model("LabResult")
    update_model("HCCDiagnosis")


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0018_alter_encounter_workflow_state_add_waiting_additional_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitaldata",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="encounter_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.encounter",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="encounter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.encounter",
            ),
        ),
        migrations.AddField(
            model_name="hccdiagnosis",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="encounter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctor.encounter",
            ),
        ),
        migrations.RunPython(backfill_encounter_ids, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="vitaldata",
            name="medical_record",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="medical_record",
        ),
        migrations.RemoveField(
            model_name="hccdiagnosis",
            name="medical_record",
        ),
    ]
