# Generated by Django 5.2.8 on 2026-01-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DM', '1:1 대화'), ('GROUP', '그룹 대화')], default='DM', max_length=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
                ('dm_user1', models.ForeignKey(blank=True, db_column='dm_user1_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_conversations_as_user1', to=settings.AUTH_USER_MODEL)),
                ('dm_user2', models.ForeignKey(blank=True, db_column='dm_user2_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_conversations_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대화방',
                'verbose_name_plural': '대화방',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('LOCAL', '로컬'), ('S3', 'AWS S3')], default='LOCAL', max_length=10)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(db_column='uploader_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '파일',
                'verbose_name_plural': '파일',
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('TEXT', '텍스트'), ('FILE', '파일'), ('MIXED', '텍스트+파일'), ('SYSTEM', '시스템')], default='TEXT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cdss_channels_redis.conversation')),
                ('sender', models.ForeignKey(db_column='sender_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cdss_channels_redis.conversation')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, db_column='last_read_message_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cdss_channels_redis.message')),
            ],
            options={
                'verbose_name': '대화방 멤버',
                'verbose_name_plural': '대화방 멤버',
                'db_table': 'conversation_members',
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='cdss_channels_redis.file')),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='cdss_channels_redis.message')),
            ],
            options={
                'verbose_name': '메시지 첨부파일',
                'verbose_name_plural': '메시지 첨부파일',
                'db_table': 'message_files',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'DM')), fields=('dm_user1', 'dm_user2'), name='unique_dm_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_member'),
        ),
        migrations.AddConstraint(
            model_name='messagefile',
            constraint=models.UniqueConstraint(fields=('message', 'file'), name='unique_message_file'),
        ),
    ]
