# Generated by Django 5.2.7 on 2025-12-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Create shared ENUM types for the entire system
        migrations.RunSQL(
            sql="""
                -- User & Authentication
                CREATE TYPE user_role_type AS ENUM ('patient', 'doctor', 'radiologist', 'clerk');
                CREATE TYPE work_role_type AS ENUM ('DOCTOR', 'RADIOLOGIST', 'CLERK');
                CREATE TYPE dept_type AS ENUM ('CLINICAL', 'SUPPORT', 'ADMIN');
                CREATE TYPE duty_status_type AS ENUM ('CONFIRMED', 'CANCELLED');

                -- Common
                CREATE TYPE gender_type AS ENUM ('Male', 'Female');
                CREATE TYPE status_type AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED');

                -- AI & Analysis
                CREATE TYPE risk_group_type AS ENUM ('LOW', 'MEDIUM', 'HIGH');

                -- Medication
                CREATE TYPE schedule_type AS ENUM ('DAILY', 'WEEKLY', 'AS_NEEDED');
                CREATE TYPE meal_timing_type AS ENUM ('BEFORE_MEAL', 'AFTER_MEAL', 'WITH_MEAL', 'ANYTIME');
                CREATE TYPE medication_status_type AS ENUM ('PENDING', 'TAKEN', 'SKIPPED', 'MISSED');

                -- Doctor
                CREATE TYPE doctor_schedule_type AS ENUM ('CLINIC', 'SURGERY', 'MEETING', 'OFF', 'VACATION');
            """,
            reverse_sql="""
                DROP TYPE IF EXISTS user_role_type CASCADE;
                DROP TYPE IF EXISTS work_role_type CASCADE;
                DROP TYPE IF EXISTS dept_type CASCADE;
                DROP TYPE IF EXISTS duty_status_type CASCADE;
                DROP TYPE IF EXISTS gender_type CASCADE;
                DROP TYPE IF EXISTS status_type CASCADE;
                DROP TYPE IF EXISTS risk_group_type CASCADE;
                DROP TYPE IF EXISTS schedule_type CASCADE;
                DROP TYPE IF EXISTS meal_timing_type CASCADE;
                DROP TYPE IF EXISTS medication_status_type CASCADE;
                DROP TYPE IF EXISTS doctor_schedule_type CASCADE;
            """
        ),
    ]
