# Generated by Django 5.2.8 on 2026-01-13 05:50

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyschedule",
            name="schedule_status",
            field=accounts.fields.DutyStatusField(
                choices=[
                    ("CONFIRMED", "확정"),
                    ("PENDING", "대기"),
                    ("CANCELLED", "취소"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
