# Generated by Django 5.2.8 on 2026-01-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dutyschedule_schedule_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='dutyschedule',
                    table='duty_schedules',
                ),
                migrations.AlterModelTable(
                    name='onlinestatus',
                    table='online_status',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    # Create DutySchedule table
                    sql="""
                        CREATE TABLE "duty_schedules" (
                            "schedule_id" serial NOT NULL PRIMARY KEY,
                            "work_role" varchar(20) NOT NULL,
                            "start_time" timestamp with time zone NOT NULL,
                            "end_time" timestamp with time zone NOT NULL,
                            "shift_type" varchar(10) NULL,
                            "created_at" timestamp with time zone NOT NULL,
                            "updated_at" timestamp with time zone NOT NULL,
                            "schedule_status" varchar(20) NOT NULL,
                            "user_id" integer NOT NULL
                        );
                        CREATE TABLE "online_status" (
                            "online_id" serial NOT NULL PRIMARY KEY,
                            "work_role" varchar(20) NOT NULL,
                            "is_online" boolean NOT NULL,
                            "last_active" timestamp with time zone NOT NULL,
                            "user_id" integer NOT NULL
                        );
                        ALTER TABLE "duty_schedules" ADD CONSTRAINT "duty_schedules_user_id_fk_auth_user_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("user_id") DEFERRABLE INITIALLY DEFERRED;
                        ALTER TABLE "online_status" ADD CONSTRAINT "online_status_user_id_fk_auth_user_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("user_id") DEFERRABLE INITIALLY DEFERRED;
                        CREATE INDEX "duty_schedules_user_id_idx" ON "duty_schedules" ("user_id");
                        CREATE INDEX "online_status_user_id_idx" ON "online_status" ("user_id");
                    """,
                    reverse_sql="""
                        DROP TABLE "online_status";
                        DROP TABLE "duty_schedules";
                    """
                )
            ]
        )
    ]
