# Generated by Django 5.2.8 on 2026-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_dutyschedule_table_alter_onlinestatus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyschedule',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='일정 거절 사유', null=True),
        ),
    ]
