# Generated by Django 5.2.8 on 2026-01-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyschedule",
            name="shift_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAY", "주간"),
                    ("EVENING", "저녁"),
                    ("NIGHT", "심야"),
                    ("OFF", "휴무"),
                ],
                max_length=10,
                null=True,
                verbose_name="근무 유형",
            ),
        ),
        migrations.CreateModel(
            name="UserSchedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("schedule_date", models.DateField()),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("VACATION", "휴가"),
                            ("CONFERENCE", "학회/세미나"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 일정",
                "verbose_name_plural": "개인 일정",
                "db_table": "user_schedules",
                "ordering": ["-schedule_date", "start_time"],
            },
        ),
    ]
