# Generated by Django 5.2.8 on 2026-01-19 02:34

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_dutyschedule_shift_type_userschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=accounts.fields.UserRoleField(blank=True, choices=[('PATIENT', '환자'), ('DOCTOR', '의사'), ('RADIOLOGIST', '영상의학과'), ('CLERK', '원무과'), ('LIS', '진단검사의학과')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dutyschedule',
            name='work_role',
            field=accounts.fields.WorkRoleField(choices=[('DOCTOR', '의사'), ('RADIOLOGIST', '영상의학과'), ('CLERK', '원무과'), ('LIS', '진단검사의학과')], max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinestatus',
            name='work_role',
            field=accounts.fields.WorkRoleField(choices=[('DOCTOR', '의사'), ('RADIOLOGIST', '영상의학과'), ('CLERK', '원무과'), ('LIS', '진단검사의학과')], max_length=20),
        ),
    ]
