# Generated by Django 5.2.7 on 2025-12-23 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("doctor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DICOMStudy",
            fields=[
                (
                    "study_uid",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("order_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "orthanc_study_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "accession_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("modality", models.CharField(blank=True, max_length=16, null=True)),
                ("body_part", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "study_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("study_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."dicom_studies',
            },
        ),
        migrations.CreateModel(
            name="DICOMSeries",
            fields=[
                (
                    "series_uid",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "orthanc_series_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("modality", models.CharField(blank=True, max_length=16, null=True)),
                ("series_number", models.IntegerField(blank=True, null=True)),
                (
                    "series_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("acquisition_datetime", models.DateTimeField(blank=True, null=True)),
                ("image_count", models.IntegerField(blank=True, null=True)),
                (
                    "slice_thickness",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "pixel_spacing",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "protocol_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        db_column="study_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiology.dicomstudy",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."dicom_series',
            },
        ),
        migrations.CreateModel(
            name="Radiology",
            fields=[
                ("radiologic_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_no", models.CharField(max_length=50, unique=True)),
                ("license_no", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="accounts.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."radiology',
            },
        ),
        migrations.CreateModel(
            name="RadiologyPatientQueue",
            fields=[
                ("rqueue_id", models.AutoField(primary_key=True, serialize=False)),
                ("modality", models.CharField(blank=True, max_length=16, null=True)),
                ("body_part", models.CharField(blank=True, max_length=64, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sample_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.patient",
                    ),
                ),
                (
                    "radiologic",
                    models.ForeignKey(
                        db_column="radiologic_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="radiology.radiology",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        db_column="study_uid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="radiology.dicomstudy",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."radiology_patient_queue',
            },
        ),
        migrations.CreateModel(
            name="RadiologyAIRun",
            fields=[
                ("run_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_type", models.CharField(blank=True, max_length=30, null=True)),
                ("model_name", models.CharField(blank=True, max_length=128, null=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        db_column="series_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiology.dicomseries",
                    ),
                ),
            ],
            options={
                "db_table": 'hospital"."radiology_ai_runs',
                "indexes": [
                    models.Index(
                        fields=["series"], name="radiology_a_series__66337e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="radiology_a_status_2dd0e7_idx"
                    ),
                ],
            },
        ),
    ]
