# Generated by Django 5.2.8 on 2026-01-08 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMStudy',
            fields=[
                ('study_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('orthanc_study_id', models.CharField(blank=True, max_length=64, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=64, null=True)),
                ('modality', models.CharField(blank=True, max_length=16, null=True)),
                ('body_part', models.CharField(blank=True, max_length=64, null=True)),
                ('study_description', models.CharField(blank=True, max_length=255, null=True)),
                ('study_datetime', models.DateTimeField(blank=True, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, db_column='encounter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.encounter')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.patient')),
            ],
            options={
                'db_table': 'hospital"."dicom_studies',
            },
        ),
        migrations.CreateModel(
            name='DICOMSeries',
            fields=[
                ('series_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('orthanc_series_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modality', models.CharField(blank=True, max_length=16, null=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('series_description', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_datetime', models.DateTimeField(blank=True, null=True)),
                ('image_count', models.IntegerField(blank=True, null=True)),
                ('slice_thickness', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pixel_spacing', models.CharField(blank=True, max_length=64, null=True)),
                ('protocol_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(db_column='study_uid', on_delete=django.db.models.deletion.CASCADE, to='radiology.dicomstudy')),
            ],
            options={
                'db_table': 'hospital"."dicom_series',
            },
        ),
        migrations.CreateModel(
            name='Radiology',
            fields=[
                ('radiologic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('employee_no', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('license_no', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.RESTRICT, to='accounts.department')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '영상의학과',
                'verbose_name_plural': '영상의학과',
                'db_table': 'hospital"."radiology',
            },
        ),
        migrations.CreateModel(
            name='RadiologyToDoctorOrder',
            fields=[
                ('rd_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', '요청됨'), ('CHECKED', '확인됨'), ('CANCELLED', '취소')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('encounter', models.ForeignKey(blank=True, db_column='encounter_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.encounter')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.patient')),
                ('radiologist', models.ForeignKey(db_column='radiologic_id', on_delete=django.db.models.deletion.RESTRICT, to='radiology.radiology')),
            ],
            options={
                'db_table': 'hospital"."radiology_to_doctor_orders',
            },
        ),
        migrations.CreateModel(
            name='RadiologyAIRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(blank=True, max_length=30, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('RUNNING', '분석중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(db_column='series_uid', on_delete=django.db.models.deletion.CASCADE, to='radiology.dicomseries')),
            ],
            options={
                'db_table': 'hospital"."radiology_ai_runs',
                'indexes': [models.Index(fields=['series'], name='radiology_a_series__66337e_idx'), models.Index(fields=['status'], name='radiology_a_status_2dd0e7_idx')],
            },
        ),
    ]
