# Generated by Django 5.2.8 on 2025-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiology',
            options={'verbose_name': '영상의학과', 'verbose_name_plural': '영상의학과'},
        ),
        migrations.AddField(
            model_name='radiology',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
