# Generated by Django 5.2.8 on 2026-01-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyairun',
            name='mask_series_uid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
