# Generated by Django 5.2.8 on 2026-01-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_ct_report'),
        ('radiology', '0002_radiologyairun_mask_series_uid'),
    ]

    operations = [
    ]
