# Generated by Codex on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_merge_20260116_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
