# Generated by Codex on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_dicomstudy_session_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='post_processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='post_processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
