# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiology", "0005_dicomstudy_post_processing_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctreport",
            name="tumor_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
