# Generated by Django 5.2.7 on 2025-12-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DURContraindication",
            fields=[
                ("dur_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dur_seq", models.IntegerField(blank=True, null=True)),
                ("ingr_code_a", models.CharField(blank=True, max_length=20, null=True)),
                ("ingr_code_b", models.CharField(blank=True, max_length=20, null=True)),
                ("contraindication_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'app"."dur_contraindication',
            },
        ),
        migrations.CreateModel(
            name="MedicationDetail",
            fields=[
                ("med_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=200)),
                ("one_dose", models.CharField(blank=True, max_length=50, null=True)),
                ("daily_count", models.CharField(blank=True, max_length=50, null=True)),
                ("total_days", models.CharField(blank=True, max_length=50, null=True)),
                ("is_taking", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'app"."medication_detail',
            },
        ),
        migrations.CreateModel(
            name="PillInfo",
            fields=[
                ("item_seq", models.BigIntegerField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=200)),
                ("entp_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "item_image",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("print_front", models.CharField(blank=True, max_length=50, null=True)),
                ("print_back", models.CharField(blank=True, max_length=50, null=True)),
                ("drug_shape", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "color_class1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "color_class2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("line_front", models.CharField(blank=True, max_length=50, null=True)),
                ("line_back", models.CharField(blank=True, max_length=50, null=True)),
                ("len_long", models.CharField(blank=True, max_length=20, null=True)),
                ("len_short", models.CharField(blank=True, max_length=20, null=True)),
                ("thick", models.CharField(blank=True, max_length=20, null=True)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "etc_otc_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ingr_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'app"."pill_info',
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("pres_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "hospital_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dispense_date", models.DateField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'app"."prescriptions',
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("profile_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigIntegerField()),
                (
                    "linked_patient_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": 'app"."user_profile',
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                ("schedule_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "schedule_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "매일"),
                            ("WEEKLY", "주간"),
                            ("AS_NEEDED", "필요시"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("times_per_day", models.IntegerField(blank=True, null=True)),
                ("time_slots", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_days", models.IntegerField(blank=True, null=True)),
                (
                    "meal_timing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BEFORE_MEAL", "식전"),
                            ("AFTER_MEAL", "식후"),
                            ("WITH_MEAL", "식사중"),
                            ("ANYTIME", "아무때나"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reminder_enabled", models.BooleanField(default=True)),
                ("reminder_advance_minutes", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "med",
                    models.ForeignKey(
                        db_column="med_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.medicationdetail",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."medication_schedule',
            },
        ),
        migrations.AddField(
            model_name="medicationdetail",
            name="pill_info",
            field=models.ForeignKey(
                db_column="item_seq",
                on_delete=django.db.models.deletion.RESTRICT,
                to="patients.pillinfo",
            ),
        ),
        migrations.AddField(
            model_name="medicationdetail",
            name="pres",
            field=models.ForeignKey(
                db_column="pres_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="profile",
            field=models.ForeignKey(
                db_column="profile_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="PhysicalHistory",
            fields=[
                ("physical_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_pregnant", models.BooleanField(default=False)),
                ("smoking_status", models.BooleanField(default=False)),
                (
                    "alcohol_freq",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("measured_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."physical_history',
            },
        ),
        migrations.CreateModel(
            name="MedicationNotification",
            fields=[
                (
                    "notification_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=False)),
                ("first_reminder_minutes", models.IntegerField(default=30)),
                ("second_reminder_minutes", models.IntegerField(default=0)),
                ("late_reminder_minutes", models.IntegerField(default=30)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_start_time", models.TimeField(blank=True, null=True)),
                ("quiet_end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."medication_notification',
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("TAKEN", "복용완료"),
                            ("SKIPPED", "건너뜀"),
                            ("MISSED", "놓침"),
                        ],
                        max_length=20,
                    ),
                ),
                ("skip_reason", models.TextField(blank=True, null=True)),
                (
                    "scheduled_dosage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "actual_dosage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("side_effects", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "med",
                    models.ForeignKey(
                        db_column="med_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.medicationdetail",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.medicationschedule",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."medication_log',
            },
        ),
        migrations.CreateModel(
            name="MedicationAdherence",
            fields=[
                (
                    "adherence_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_scheduled", models.IntegerField(blank=True, null=True)),
                ("total_taken", models.IntegerField(blank=True, null=True)),
                ("total_skipped", models.IntegerField(blank=True, null=True)),
                ("total_missed", models.IntegerField(blank=True, null=True)),
                (
                    "adherence_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("current_streak_days", models.IntegerField(blank=True, null=True)),
                ("longest_streak_days", models.IntegerField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "med",
                    models.ForeignKey(
                        db_column="med_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.medicationdetail",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."medication_adherence',
            },
        ),
        migrations.CreateModel(
            name="DURLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_drug_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "conflict_drug_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "violated_dur",
                    models.ForeignKey(
                        db_column="violated_dur_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="patients.durcontraindication",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."dur_log',
            },
        ),
        migrations.CreateModel(
            name="DiseaseHistory",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "disease_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("disease_name", models.CharField(max_length=100)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("severity_level", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."disease_history',
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("allergy_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "allergy_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "trigger_agent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reaction_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."allergy',
            },
        ),
        migrations.CreateModel(
            name="Vital",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("record_date", models.DateTimeField()),
                ("sbp", models.IntegerField(blank=True, null=True)),
                ("dbp", models.IntegerField(blank=True, null=True)),
                ("blood_sugar", models.IntegerField(blank=True, null=True)),
                ("memo", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="profile_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": 'app"."vital',
            },
        ),
    ]
