# Generated by Django 5.2.8 on 2026-01-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        # 1. password 필드 추가 (기존 데이터가 없다면 null=True로 시작)
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, default=''),
            preserve_default=False,
        ),
        # 2. user_id에 unique 제약 조건 추가 (중복 방지)
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
