# Generated by Django 5.2.8 on 2026-01-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('patients', '0004_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSyncRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '승인대기'), ('APPROVED', '승인완료'), ('REJECTED', '거절됨')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('processed_by', models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.administration')),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='patients.userprofile')),
            ],
            options={
                'db_table': 'app"."app_sync_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
